# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-16 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default=b'd7d83ffc-1e38-4179-ac88-732bbdb49362', editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
