# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-16 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_auto_20181116_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
